sudo: required
services:
  - docker

before_install:
  - docker build -t dcattera/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run dcattera/react-test npm run test -- --coverage

after_success:
  - docker build -t dcattera/multi-client ./client
  - docker build -t dcattera/multi-nginx ./nginx
  - docker build -t dcattera/multi-server ./server
  - docker build -t dcattera/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push dcattera/multi-client
  - docker push dcattera/multi-nginx
  - docker push dcattera/multi-server
  - docker push dcattera/multi-worker      

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker" 
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-827956149269"
  bucket_path: "docker-multi"
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"